version: 2.1
jobs:
  build:
    docker:
      - image: okta10/docker:ubuntu
    steps:
      - run:
          name: Building Kernel
          command: |
            wget https://raw.githubusercontent.com/zacky46/kernel-script/ginkgo/sync.sh
            bash sync.sh stable clang
            cd kernel
            wget https://raw.githubusercontent.com/zacky46/kernel-script/ginkgo/final.sh
            bash final.sh clang
