version: 2.1
jobs:
  build:
    docker:
      - image: okta10/docker:ubuntu
    steps:
      - run:
          name: Building Kernel
          command: |
            wget https://raw.githubusercontent.com/zacky46/kernel-script/kernelsu-whyred/sync.sh
            bash sync.sh stable clang
            cd kernel
            wget https://raw.githubusercontent.com/zacky46/kernel-script/kernelsu-whyred/dtb.sh
            bash dtb.sh whyred clang qpnp
            git apply qti.patch
            bash dtb.sh whyred clang qti
            git restore .
            wget https://raw.githubusercontent.com/zacky46/kernel-script/kernelsu-whyred/run.sh
            bash run.sh whyred newcam clang
            bash run.sh whyred oldcam clang
            wget https://raw.githubusercontent.com/zacky46/kernel-script/kernelsu-whyred/final.sh
            bash final.sh clang
